declare module 'mocha-jsdom' {
    function jsdom(options?: any): any;
    export = jsdom;
}

declare module 'jsdom-global' {
    function jsdom(options?: any): any;
    export = jsdom;
}

// Generated by typings
// Type definitions for redux-thunk
// Project: https://github.com/gaearon/redux-thunk
// Definitions by: Qubo <https://github.com/tkqubo>
// Definitions: https://github.com/borisyankov/DefinitelyTyped

declare module ReduxThunk {
    export interface Thunk extends Redux.Middleware {}
    export interface ThunkInterface {
      <T>(dispatch: Redux.Dispatch, getState?: () => T): any;
    }
}

declare module 'redux-thunk' {
    const thunk: ReduxThunk.Thunk;
    export default thunk;
}